---
include:
  - board: nice_nano/nrf52840/zmk
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne\"
    artifact-name: corne_left_oled_rgb
    snippet: rgb-config
  - board: nice_nano/nrf52840/zmk
    shield: corne_right nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne\"
    artifact-name: corne_right_oled_rgb
    snippet: rgb-config
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset
